// source: fileServicePlatform.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DeleteRequest', null, global);
goog.exportSymbol('proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DeleteResponse', null, global);
goog.exportSymbol('proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadRequest', null, global);
goog.exportSymbol('proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadResponse', null, global);
goog.exportSymbol('proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListRequest', null, global);
goog.exportSymbol('proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListResponse', null, global);
goog.exportSymbol('proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.HelloReply', null, global);
goog.exportSymbol('proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.HelloRequest', null, global);
goog.exportSymbol('proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadRequest', null, global);
goog.exportSymbol('proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.HelloRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.HelloRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.HelloRequest.displayName = 'proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.HelloRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.HelloReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.HelloReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.HelloReply.displayName = 'proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.HelloReply';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadRequest.displayName = 'proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadResponse.displayName = 'proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadRequest.displayName = 'proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadResponse.displayName = 'proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListRequest.displayName = 'proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListResponse.repeatedFields_, null);
};
goog.inherits(proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListResponse.displayName = 'proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DeleteRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DeleteRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DeleteRequest.displayName = 'proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DeleteRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DeleteResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DeleteResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DeleteResponse.displayName = 'proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DeleteResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.HelloRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.HelloRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.HelloRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.HelloRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.HelloRequest}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.HelloRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.HelloRequest;
  return proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.HelloRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.HelloRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.HelloRequest}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.HelloRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.HelloRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.HelloRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.HelloRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.HelloRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.HelloRequest.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.HelloRequest} returns this
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.HelloRequest.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.HelloReply.prototype.toObject = function(opt_includeInstance) {
  return proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.HelloReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.HelloReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.HelloReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    message: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.HelloReply}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.HelloReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.HelloReply;
  return proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.HelloReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.HelloReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.HelloReply}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.HelloReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.HelloReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.HelloReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.HelloReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.HelloReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string message = 1;
 * @return {string}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.HelloReply.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.HelloReply} returns this
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.HelloReply.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    file: msg.getFile_asB64(),
    filename: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadRequest}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadRequest;
  return proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadRequest}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setFile(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setFilename(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFile_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getFilename();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional bytes file = 1;
 * @return {!(string|Uint8Array)}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadRequest.prototype.getFile = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes file = 1;
 * This is a type-conversion wrapper around `getFile()`
 * @return {string}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadRequest.prototype.getFile_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getFile()));
};


/**
 * optional bytes file = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getFile()`
 * @return {!Uint8Array}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadRequest.prototype.getFile_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getFile()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadRequest} returns this
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadRequest.prototype.setFile = function(value) {
  return jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * optional string fileName = 2;
 * @return {string}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadRequest.prototype.getFilename = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadRequest} returns this
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadRequest.prototype.setFilename = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    success: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    url: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadResponse}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadResponse;
  return proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadResponse}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSuccess(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setUrl(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSuccess();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getUrl();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional bool success = 1;
 * @return {boolean}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadResponse.prototype.getSuccess = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadResponse} returns this
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadResponse.prototype.setSuccess = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional string url = 2;
 * @return {string}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadResponse.prototype.getUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadResponse} returns this
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.UploadResponse.prototype.setUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    filename: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadRequest}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadRequest;
  return proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadRequest}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setFilename(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFilename();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string fileName = 1;
 * @return {string}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadRequest.prototype.getFilename = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadRequest} returns this
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadRequest.prototype.setFilename = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    file: msg.getFile_asB64(),
    filename: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadResponse}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadResponse;
  return proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadResponse}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setFile(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setFilename(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFile_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getFilename();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional bytes file = 1;
 * @return {!(string|Uint8Array)}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadResponse.prototype.getFile = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes file = 1;
 * This is a type-conversion wrapper around `getFile()`
 * @return {string}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadResponse.prototype.getFile_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getFile()));
};


/**
 * optional bytes file = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getFile()`
 * @return {!Uint8Array}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadResponse.prototype.getFile_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getFile()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadResponse} returns this
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadResponse.prototype.setFile = function(value) {
  return jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * optional string fileName = 2;
 * @return {string}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadResponse.prototype.getFilename = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadResponse} returns this
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DownloadResponse.prototype.setFilename = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListRequest}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListRequest;
  return proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListRequest}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    filenameList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListResponse}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListResponse;
  return proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListResponse}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addFilename(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFilenameList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
};


/**
 * repeated string fileName = 1;
 * @return {!Array<string>}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListResponse.prototype.getFilenameList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListResponse} returns this
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListResponse.prototype.setFilenameList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListResponse} returns this
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListResponse.prototype.addFilename = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListResponse} returns this
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.GetFileListResponse.prototype.clearFilenameList = function() {
  return this.setFilenameList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DeleteRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DeleteRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DeleteRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DeleteRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    filename: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DeleteRequest}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DeleteRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DeleteRequest;
  return proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DeleteRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DeleteRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DeleteRequest}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DeleteRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setFilename(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DeleteRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DeleteRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DeleteRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DeleteRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFilename();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string fileName = 1;
 * @return {string}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DeleteRequest.prototype.getFilename = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DeleteRequest} returns this
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DeleteRequest.prototype.setFilename = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DeleteResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DeleteResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DeleteResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DeleteResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    success: jspb.Message.getBooleanFieldWithDefault(msg, 1, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DeleteResponse}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DeleteResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DeleteResponse;
  return proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DeleteResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DeleteResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DeleteResponse}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DeleteResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSuccess(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DeleteResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DeleteResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DeleteResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DeleteResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSuccess();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
};


/**
 * optional bool success = 1;
 * @return {boolean}
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DeleteResponse.prototype.getSuccess = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DeleteResponse} returns this
 */
proto.xyz.yingshaoxo.fileServicePlatform.grpc.main.DeleteResponse.prototype.setSuccess = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


goog.object.extend(exports, proto.xyz.yingshaoxo.fileServicePlatform.grpc.main);
